#!/bin/sh

case $1 in
   config)

        cat << 'EOM'
graph_title Licht
graph_vlabel mV
Light.label Wohnzimmer
EOM

exit 0;;
esac

/usr/bin/ruby1.9.3 /mnt/RAID5_intern/bernd/documents/Projekte/serialreader.git/raw_light2munin.rb

