#!/bin/sh

case $1 in
   config)

        cat << 'EOM'
graph_title Temperatur
graph_vlabel Celsius
nSv_h.label Celsius
EOM

exit 0;;
esac

#path to serialreader.rb
/usr/local/rvm/bin/ruby /home/x42/serialreader.git/serialreader.rb -m munin -d /dev/ttyUSB1
