#!/bin/sh

case $1 in
   config)

        cat << 'EOM'
graph_title Temperatur
graph_vlabel Celsius
graph_args --lower-limit 20 --upper-limit 24
Temp.label Wohnzimmer
EOM

exit 0;;
esac

/home/x42/projekte/serialreader.git/raw_temp2munin.rb

